### ISSUE TITLE
Suport for redmine 3.2

### ISSUE THREAD

**Issue by nvolpini** [paginagmbh/redmine_project_alias_2#1]
Hello, is there any plan to support Redmine version 3.2 ?

**Comment by tofi86** [comment]
Isn't it working anymore? have you tested?

**Comment by nvolpini** [comment]
Yes, it seems to be working (the alias function, links creation,etc), however when I visit the projects page and error happen and I confirmed that it works fine if I disable the plugin. 

```
Started GET "/projects" for 192.168.0.10 at 2016-01-15 08:53:17 -0200
Processing by ProjectsController#index as HTML
  Current user: neimar (id=4)
  Rendered projects/index.html.erb within layouts/base (16.5ms)
Completed 500 Internal Server Error in 28ms (ActiveRecord: 3.9ms)

ActiveRecord::RecordNotFound (Couldn't find all Projects with 'id': (first, {:conditions=>["identifier = :s OR LOWER(name) = :s", {:s=>"focco-java"}]}) [WHERE (projects.status <> 9)] (found 0 results, but was looking for 2)):
  app/helpers/application_helper.rb:587:in `block (2 levels) in textilizable'
  app/helpers/application_helper.rb:586:in `each'
  app/helpers/application_helper.rb:586:in `block in textilizable'
  app/helpers/application_helper.rb:607:in `parse_non_pre_blocks'
  app/helpers/application_helper.rb:585:in `textilizable'
  app/helpers/projects_helper.rb:69:in `block in render_project_hierarchy'
  app/helpers/application_helper.rb:282:in `block in render_project_nested_lists'
  app/helpers/application_helper.rb:267:in `each'
  app/helpers/application_helper.rb:267:in `render_project_nested_lists'
  app/helpers/projects_helper.rb:66:in `render_project_hierarchy'
  app/views/projects/index.html.erb:12:in `_app_views_projects_index_html_erb__1625633549337987863_46853320'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

The /projects page Is the only thing that doesn't work. I suspected that is related to this plugin because if I disable it, it works fine.

PS: I was using the original plugin when I had redmine version 2.5 installed, after I upgraded redmine to version 3.2 last week I had to install your fork of the plugin. 

Please let me know if I can do something to help you isolate the problem.

Thanks in advance.
Neimar

**Comment by tofi86** [comment]
okay, thanks for investigating and sending the logfile.
Will have a look on the weekend...

**Comment by nvolpini** [comment]
Let me know if you need more information. 
Thanks.

**Comment by nvolpini** [comment]
I found another situation where the same error happens when opening an issue and I believe I know the exactly cause...

```
Started GET "/issues/2732" for 192.168.0.10 at 2016-01-15 11:17:52 -0200
Processing by IssuesController#show as HTML
  Parameters: {"id"=>"2732"}
  Current user: neimar (id=4)
  Rendered issues/_action_menu.html.erb (4.4ms)
  Rendered attachments/_links.html.erb (4.1ms)
  Rendered issue_relations/_form.html.erb (1.5ms)
  Rendered issues/_relations.html.erb (14.3ms)
  Rendered issues/_history.html.erb (204.2ms)
  Rendered issues/show.html.erb within layouts/base (255.5ms)
Completed 500 Internal Server Error in 332ms (ActiveRecord: 21.7ms)

ActiveRecord::RecordNotFound (Couldn't find all Projects with 'id': (first, {:conditions=>["identifier = :s OR LOWER(name) = :s", {:s=>"solidworks"}]}) [WHERE (projects.status <> 9)] (found 0 results, but was looking for 2)):
  app/helpers/application_helper.rb:587:in `block (2 levels) in textilizable'
  app/helpers/application_helper.rb:586:in `each'
  app/helpers/application_helper.rb:586:in `block in textilizable'
  app/helpers/application_helper.rb:607:in `parse_non_pre_blocks'
  app/helpers/application_helper.rb:585:in `textilizable'
  app/helpers/journals_helper.rb:43:in `render_notes'
  app/views/issues/_history.html.erb:24:in `block in _app_views_issues__history_html_erb___390672801795377320_78521760'
  app/views/issues/_history.html.erb:2:in `each'
  app/views/issues/_history.html.erb:2:in `_app_views_issues__history_html_erb___390672801795377320_78521760'
  app/views/issues/show.html.erb:124:in `_app_views_issues_show_html_erb__809778066703002816_70148036647580'
  app/controllers/issues_controller.rb:118:in `block (2 levels) in show'
  app/controllers/issues_controller.rb:115:in `show'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

```

I did some digging and the error happens whenever I use redmine's expression for referencing a project. In the error above one of the issue's "journals" do references a project like this:

```
Bla, bla, bla
See project:solidworks
```

If the above expression is found (project:XXXX) and has to be parsed, in issue's journals, description or wherever, the error happen, even if the project being referenced doesn't have an alias.

The original problem I reported in /projects page is because I use that expression in some project's description, once the /projects page shows the project description the error happens there too.

Hope it helps.

**Comment by tofi86** [comment]
Confirmed. Let's see whether I find a solution for that...

**Comment by tofi86** [comment]
This is fixed. A new version has been released.

**Comment by nvolpini** [comment]
Worked like a charm!!
Thank you very much.
